# default basic config
# these values will be overwritten by scripts/opusfilter.py

common:

  output_directory: 

steps:

  - type: filter
    parameters:
      inputs: []
      outputs: []
      filters:
        - LengthFilter:
            unit: word
            min_length: 1
            max_length: 512
            pass_empty: true

        - LongWordFilter:
            threshold: 40

        - HtmlTagFilter: {}

        - PunctuationFilter:
            threshold: 0.6
            pass_empty: true
          module: customfilters

        - DigitsFilter:
            threshold: 0.6
            pass_empty: true
          module: customfilters
